data_module:
  name: mnist-dm
  args:
    root_dir: ./load/mnist
    batch_size: 32
  
train_wrapper:
  name: base
  args:
    model_spec:
      name: resnet18
      args:
        num_classes: 10
    
    loss_spec:
      name: mnist_ce
    
    optim_spec:
      name: Adam
      args:
        lr: 1.e-4
        betas: [0.9, 0.999]

trainer_params:
  max_epochs: 100
  strategy: ddp

checkpoint:
  every_n_epochs: 1

seed: 42

    